const express = require('express');
const mysql = require('mysql2');
const cors = require('cors');
const path = require('path');

const app = express();

// Middleware setup
app.use(express.json({ limit: '10mb' })); // Increased limit to handle face descriptor/image payloads if needed
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use(cors());

// Serve static files from the 'public' folder
app.use(express.static(path.join(__dirname, 'public')));

// Explicit root route handler
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Database connection configuration
const db = mysql.createConnection({
    host: process.env.DB_HOST || 'localhost',
    user: process.env.DB_USER || 'u958815946_ai_attend_user',
    password: process.env.DB_PASSWORD || 'Indicraft@2026',
    database: process.env.DB_NAME || 'u958815946_ai_attend'
});

db.connect(err => {
    if (err) {
        console.error('Database connection failed:', err);
    } else {
        console.log('Connected to MySQL database successfully.');
    }
});

/**
 * 1. EMPLOYEE MASTER & FACE DATA REGISTRATION API
 * Registers an employee along with their AI face descriptors/vectors 
 * generated by a frontend face recognition library (e.g., face-api.js).
 */
app.post('/api/employees', (req, res) => {
    const { userId, name, faceDescriptor } = req.body;

    if (!userId || !name || !faceDescriptor) {
        return res.status(400).json({ status: 'error', message: 'Missing required employee fields or face data.' });
    }

    // Store faceDescriptor as a JSON string in MySQL
    const query = `INSERT INTO employees (user_id, name, face_descriptor) VALUES (?, ?, ?) 
                   ON DUPLICATE KEY UPDATE name = VALUES(name), face_descriptor = VALUES(face_descriptor)`;

    db.query(query, [userId, name, JSON.stringify(faceDescriptor)], (err, result) => {
        if (err) {
            console.error('Error saving employee:', err);
            return res.status(500).json({ status: 'error', message: 'Database error: ' + err.sqlMessage });
        }
        res.json({ status: 'success', message: 'Employee and face profile configured successfully!' });
    });
});

/**
 * 2. FETCH ALL REGISTERED EMPLOYEES & FACE DESCRIPTORS
 * Used by the frontend AI model to load known faces into memory for real-time comparison.
 */
app.get('/api/employees', (req, res) => {
    const query = `SELECT user_id, name, face_descriptor FROM employees`;
    db.query(query, (err, results) => {
        if (err) {
            console.error('Error fetching employees:', err);
            return res.status(500).json({ status: 'error', message: 'Failed to fetch employee master data.' });
        }
        // Parse JSON face descriptors before sending back to client
        const employees = results.map(emp => ({
            userId: emp.user_id,
            name: emp.name,
            faceDescriptor: JSON.parse(emp.face_descriptor)
        }));
        res.json({ status: 'success', employees });
    });
});

/**
 * 3. AI ATTENDANCE LOGGING API
 * Automatically triggered once the AI model on the frontend or backend recognizes a face 
 * and matches it to a specific userId.
 */
app.post('/api/attendance', (req, res) => {
    const { userId } = req.body;
    
    if (!userId) {
        return res.status(400).json({ status: 'error', message: 'User ID is missing from recognition payload.' });
    }
    
    // Verify if user exists in the Employee Master first
    const verifyUserQuery = `SELECT * FROM employees WHERE user_id = ?`;
    db.query(verifyUserQuery, [userId], (err, userResults) => {
        if (err) {
            return res.status(500).json({ status: 'error', message: 'Database error: ' + err.sqlMessage });
        }
        
        if (userResults.length === 0) {
            return res.status(404).json({ status: 'error', message: 'Recognized face does not match any configured employee.' });
        }

        // Check if attendance is already marked for today
        const checkQuery = `SELECT * FROM attendance WHERE user_id = ? AND DATE(timestamp) = CURDATE()`;
        db.query(checkQuery, [userId], (err, results) => {
            if (err) {
                return res.status(500).json({ status: 'error', message: 'Database check failed: ' + err.sqlMessage });
            }
            
            if (results.length > 0) {
                return res.status(200).json({ status: 'exists', message: `Attendance already marked today for ${userResults[0].name}.` });
            }
            
            // Log new attendance
            const insertQuery = `INSERT INTO attendance (user_id) VALUES (?)`;
            db.query(insertQuery, [userId], (err, result) => {
                if (err) {
                    return res.status(500).json({ status: 'error', message: 'SQL Error: ' + err.sqlMessage });
                }
                res.json({ 
                    status: 'success', 
                    message: `Attendance marked successfully for ${userResults[0].name}!` 
                });
            });
        });
    });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`AI Attendance Server running on port ${PORT}`));
